"""init

Revision ID: d0db2122d9ad
Revises: 
Create Date: 2026-02-07 20:52:03.539024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0db2122d9ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auteur',
    sa.Column('id_auteur', sa.Integer(), nullable=False),
    sa.Column('nom_auteur', sa.String(length=120), nullable=False),
    sa.Column('prenom_auteur', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_auteur')
    )
    op.create_table('categorie',
    sa.Column('id_cat', sa.Integer(), nullable=False),
    sa.Column('nom_cat', sa.String(length=120), nullable=False),
    sa.Column('champ', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_cat'),
    sa.UniqueConstraint('nom_cat')
    )
    op.create_table('livre',
    sa.Column('id_livre', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=40), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['categorie.id_cat'], ),
    sa.PrimaryKeyConstraint('id_livre'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('livre_auteur',
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id_auteur'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['livre_id'], ['livre.id_livre'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('livre_id', 'auteur_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livre_auteur')
    op.drop_table('livre')
    op.drop_table('categorie')
    op.drop_table('auteur')
    # ### end Alembic commands ###
